live_config_reload = true

[cursor]
unfocused_hollow = true

[cursor.style]
blinking = "on"
shape = "Underline"

[env]
TERM = "xterm-256color"

[font]
size = 11

[font.bold]
family =  'JetBrainsMono Nerd Font Mono' # "Geist Mono Variable"
style = "Bold"

[font.bold_italic]
family =  'JetBrainsMono Nerd Font Mono' # "Geist Mono Variable"
style = "Bold Italic"

[font.italic]
family =  'JetBrainsMono Nerd Font Mono' # "Geist Mono Variable"
style = "Italic"

[font.normal]
family =  'JetBrainsMono Nerd Font Mono' # "Geist Mono Variable"
style = "Regular"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 10

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[shell]
program = "powershell"

[window]
decorations = "full"
startup_mode = "Windowed"
opacity = 1
# decorations = "transparent"
# startup_mode = "Maximized"

# [window.dimensions]
# columns = 133
# lines = 40

# [window.padding]
# x = 5
# y = 5

# [window.position]
# x = 100
# y = 100

# Colors (Dracula+)

[colors.primary]
background = '#212121'
foreground = '#F8F8F2'

[colors.cursor]
text = '#0E1415'
cursor = '#ECEFF4'

[colors.normal]
black = '#21222C'
red = '#FF5555'
green = '#50FA7B'
yellow = '#FFCB6B'
blue = '#82AAFF'
magenta = '#C792EA'
cyan = '#8BE9FD'
white = '#BBBBBB'

[colors.bright]
black = '#545454'
red = '#FF6E6E'
green = '#69FF94'
yellow = '#FFCB6B'
blue = '#D6ACFF'
magenta = '#FF92DF'
cyan = '#A4FFFF'
white = '#F8F8F2'
