# Colors (Dracula+correct)

[colors.primary]
background = '#212121'
foreground = '#F8F8F2'

[colors.cursor]
text = '#0E1415'
cursor = '#ECEFF4'

[colors.normal]
black = '#21222C'
red = '#FF5555'
green = '#50FA7B'
yellow = '#F1FA8C'
blue = '#BD93F9'
magenta = '#FF79C6'
cyan = '#8BE9FD'
white = '#BBBBBB'

[colors.bright]
black = '#545454'
red = '#FF6E6E'
green = '#69FF94'
yellow = '#FFCB6B'
blue = '#D6ACFF'
magenta = '#FF92DF'
cyan = '#A4FFFF'
white = '#F8F8F2'
